# Example configuration for nfrx
port: 8080                    # HTTP listen port for the public API
metrics_addr: ":8080"        # Prometheus metrics listen address
# log_level: info             # logging verbosity (all, debug, info, warn, error, fatal, none)
# api_key: ""                # client API key required for HTTP requests
# client_key: ""             # shared key clients must present when registering
request_timeout: 120s         # request timeout without worker activity
drain_timeout: 5m             # wait time for in-flight requests on shutdown
# max_parallel_embeddings: 8  # maximum number of workers to split embeddings across
# allowed_origins: []         # comma separated list of allowed CORS origins
# redis_addr: redis://127.0.0.1:6379/0  # redis connection URL for server state
