FROM golang:1.22 AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/llamapool-worker ./cmd/llamapool-worker

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/llamapool-worker /llamapool-worker
ENTRYPOINT ["/llamapool-worker"]
