name: macOS Build
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build (Release)
        env:
          DEVELOPMENT_TEAM: ${{ secrets.AC_TEAM_ID }}
        run: |
          xcodebuild -project desktop/macos/nfrx/nfrx.xcodeproj -scheme nfrx -configuration Release -archivePath build/nfrx.xcarchive archive
          xcodebuild -exportArchive -archivePath build/nfrx.xcarchive -exportOptionsPlist ci/exportOptions.plist -exportPath build/export
      - name: Create DMG
        run: |
          ci/create-dmg.sh build/export/nfrx.app build/Nfrx.dmg
      - name: Notarize
        env:
          AC_API_KEY_ID: ${{ secrets.AC_API_KEY_ID }}
          AC_API_ISSUER_ID: ${{ secrets.AC_API_ISSUER_ID }}
          AC_API_P8: ${{ secrets.AC_API_P8 }}
        run: ci/notarize.sh build/Nfrx.dmg
      - name: Staple
        run: xcrun stapler staple build/Nfrx.dmg
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nfrx-macOS
          path: build/Nfrx.dmg
